apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-demo
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8089 # expose
      targetPort: 80 # pod running